const WALLET_PRIVATEKEY = 'WALLET_PRIVATEKEY'
const WALLET_METAMASK = 'WALLET_METAMASK'
const WALLET_METAMASK_SNAP = 'WALLET_METAMASK_SNAP'
const WALLET_MAGIC_LINK = 'WALLET_MAGIC_LINK'
const WALLET_CONNECT = 'WALLET_CONNECT'

export const WALLET_KIND = {
  WALLET_PRIVATEKEY,
  WALLET_METAMASK,
  WALLET_METAMASK_SNAP,
  WALLET_MAGIC_LINK,
  WALLET_CONNECT
}
