const WALLET_PRIVATEKEY = 'WALLET_PRIVATEKEY'
const WALLET_METAMASK = 'WALLET_METAMASK'
const WALLET_METAMASK_SNAP = 'WALLET_METAMASK_SNAP'

export const WALLET_KIND = {
  WALLET_PRIVATEKEY,
  WALLET_METAMASK,
  WALLET_METAMASK_SNAP
}
